### ISSUE TITLE
Mongodb catalog

### ISSUE THREAD

**Issue by djcenox** [rancher/rancher-catalog#111]
Looks like something is missing in the mongo image, cause the script expect curl. This is a missing from mongo-conf image.
/opt/rancher/bin/lowest_idx.sh: line 9: curl: command not found
/opt/rancher/bin/lowest_idx.sh: line 24: [: : integer expression expected

**Comment by dsvmacdonald** [comment]
Agreed...I can run the catalog (on multiple hosts in Digital Ocean) but the replica sets cannot find each other.  Loos like the configuration never happened. 

Here is the log for one of the mongo instances:

3/12/2016 7:25:18 PM/opt/rancher/bin/lowest_idx.sh: line 9: curl: command not found
3/12/2016 7:25:18 PM/opt/rancher/bin/lowest_idx.sh: line 24: [: : integer expression expected
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=minerva-mongodb_mongo_1
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] db version v3.0.10
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] git version: 1e0512f8453d103987f5fbfb87b71e9a131c2a60
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] build info: Linux ip-10-145-79-83 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] allocator: tcmalloc
3/12/2016 7:25:19 PM2016-03-13T00:25:19.017+0000 I CONTROL  [initandlisten] options: { replication: { replSet: "minerva" }, storage: { mmapv1: { smallFiles: true } } }
3/12/2016 7:25:19 PM2016-03-13T00:25:19.039+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
3/12/2016 7:25:19 PM2016-03-13T00:25:19.039+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
3/12/2016 7:25:19 PM2016-03-13T00:25:19.109+0000 I JOURNAL  [durability] Durability thread started
3/12/2016 7:25:19 PM2016-03-13T00:25:19.109+0000 I JOURNAL  [journal writer] Journal writer thread started
3/12/2016 7:25:19 PM2016-03-13T00:25:19.110+0000 I CONTROL  [initandlisten] 
3/12/2016 7:25:19 PM2016-03-13T00:25:19.110+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I CONTROL  [initandlisten] 
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I CONTROL  [initandlisten] 
3/12/2016 7:25:19 PM2016-03-13T00:25:19.111+0000 I INDEX    [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
3/12/2016 7:25:19 PM2016-03-13T00:25:19.150+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
3/12/2016 7:25:19 PM2016-03-13T00:25:19.150+0000 I STORAGE  [FileAllocator] creating directory /data/db/_tmp
3/12/2016 7:25:19 PM2016-03-13T00:25:19.152+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.0, size: 16MB,  took 0 secs
3/12/2016 7:25:19 PM2016-03-13T00:25:19.158+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument Did not find replica set configuration document in local.system.replset
3/12/2016 7:25:19 PM2016-03-13T00:25:19.160+0000 I NETWORK  [initandlisten] waiting for connections on port 27017

**Comment by dsvmacdonald** [comment]
Curl is missing!  I ssh into running container and there is no curl...so lowest_idx.sh is not able to contact the rancher meta data service and find the other members of the replica set.

**Comment by cloudnautique** [comment]
There is a pr coming to fix.

**Comment by cloudnautique** [comment]
MongoDb entry has moved to the community catalog.
