### ISSUE TITLE
Add scheduling to options in catalog entries

### ISSUE THREAD

**Issue by guruvan** [rancher/rancher-catalog#146]
Catalog entries are apparently intended to only be run on "any available host" - this doesn't meet with our networking security requirements, and other requirements. 

Some services **MUST** be launched on specific hosts which may only be determined via host_labels or some similar mechanism (other than those automatically determined by scheduler like port availability) 

Allowing certain features present in "normal" stack creation to be available in Catalog stack creation would allow us to launch from the catalog. Without this, to run a stack form the catalog means to create via catalog, edit the compose files or upgrade - upgrades are not universally successful yet, so this means the stack is created and deleted and replaced (which has currently detrimental effects if you attempt this with convoy) 

Thanks!

**Comment by rdigiorgio** [comment]
I also am asking myself this question right now.
Let's imagine I only want to scale convoy-nfs to specific nodes of my environment that require a file share. How am I supposed to implement this ? Should I extend the "official" catalog to add my scheduling rules to docker-compose.yml file ?

**Comment by pwFoo** [comment]
Scheduling to the right host should be user choice during deployment by catalog service!

**Comment by deniseschannon** [comment]
With the introductions of bindings (which should be available in v1.2), this will be possible in the API/rancher-compose. It still needs UI support 

https://github.com/rancher/rancher/issues/2852
