### ISSUE TITLE
[traefik] Stacks with mixed-case names generate incorrect rules

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher-catalog#151]
If a stack has a mixedcase name (eg, TestStack) then the Traefik Host matching rule created will be something like "Host:TestStack.local".  Unfortunately, this match is case-sensitive, and so when you try to use "teststack.local" it fails to match and returns a 404.

The rules template should use toLower to lowercate the stackname (and service name if appropriate) when outputting the Host rules.

(Fix in pull req https://github.com/rawmind0/rancher-traefik/pull/2 )

**Comment by deniseschannon** [comment]
Traefik has been moved to the community catalog. @sshipway if you are still facing issues, please open an issue in that repo.

https://github.com/rancher/community-catalog/tree/master/templates/traefik
