### ISSUE TITLE
Default "random" value or type "random-password"

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher-catalog#152]
Most of the frameworks nodays need a salt, from registry, every rails app and many more.
Letting a user enter it is not really useful, so most of the catalogs currently provide a default value.

This ends up being a security issue since a lot of users doe not change it, since they expect it to be generated, since its is a password field ( hidden ) and its pre-populated. This results in a lot of instances with the same salt.

What about adding either a type "random-password" or adding a macro for default like generate_string(15) - 15 being the length?

**Comment by deniseschannon** [comment]
@EugenMayer This would be a request for our catalog-service, which should be requested in rancher/rancher. Thanks!
