### ISSUE TITLE
Severe: On catalog/stack upgrade settings are lost in several cases

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher-catalog#183]
**reproduction:**

1. You install a catalog of any kind

2. It become very common to use "upgrade-button" (https://goo.gl/8hW5Mg) to reconfigure / adjust a stack configuration which has been deployed from a catalog.

3. When new catalog version is available and you press on upgrade-stack (under stacks) now the form for the questions is shown.

**Result:**
The form carries the value from 1, not from 2.

Expected: all values changed in 2 are applied in that form

**Issue:**
If the user / admin does not know / remember that this stack has been adjusted, he will just press save, resulting in any kind of issues, even data loss or rather split e.g. when volume-configuration has been changed.

**Comment by vincent99** [comment]
As exhaustively discussed on IRC, manual changes to individual services will be overwritten by the new template version, but you could be able to "upgrade" a template to the same version: https://github.com/rancher/ui/pull/801
