### ISSUE TITLE
Route53 External DNS Service - Private vs Public DNS

### ISSUE THREAD

**Issue by gitlab-pano** [rancher/rancher-catalog#214]
Is there a way to use this service to add both public and private DNS entries?

I have a public and private zone of the same name.  I have it configured to target the zone ID of the private domain.  Can I add the Zone ID of the public zone as well? Or if I leave the Zone ID out would it be smart enough to tell which zone to put the entries in?  Or would all the entries go in the public zone since it is listed first?

Could I perhaps have two separate instances of this service?

**Comment by janeczku** [comment]
To update multiple zones you can an instance of the external DNS service for each of them. Just make sure that you specify the respective Zone ID if the zones have the same name.

**Comment by gitlab-pano** [comment]
Will it know to produce the public IP address for things that are running on a public subnet?

**Comment by deniseschannon** [comment]
@gitlab-pano If you still have questions, can you please open them in rancher/rancher repo? We are closing down the issues in this repo.
