### ISSUE TITLE
route53, kubernetes,  convoy-nfs, and k8 stacks are broken

### ISSUE THREAD

**Issue by seanhoughton** [rancher/rancher-catalog#216]
Pull request https://github.com/rancher/rancher-catalog/pull/215 was merged, but added invalid values which result in 

`Error unmarshalling config.yml under template: DATA/library/templates/route53, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"`

This results in an empty tile in the catalog browser and none of the stacks can be created.

**Comment by deniseschannon** [comment]
This should be fixed now. If not, please open an issue in rancher/rancher.
