### ISSUE TITLE
Template Category grouped in git directories 

### ISSUE THREAD

**Issue by lavvy** [rancher/rancher-catalog#30]
Sometimes I feel  directories should be used to group various templates in the repo.  At least that will ease discovery from github side,  particularly now that pull requests are now comming in.  To avoid cluttering in the future

**Comment by deniseschannon** [comment]
@lavvy Directories are used to group templates. I'm not too sure if you have other concerns. If so, please open them in rancher, as I'm going to close the issues for this repo.
