### ISSUE TITLE
GlusterFS sync problem

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher-catalog#44]
im making some tests with glusterfs but when i try to scale up the new node don't sync any data from glusterfs cluster. 
the first 3 container's have all data inside him, but in new container's the storage path `/data/glusterfs/brick1/example` remain empty. 
Then i scale down to 2 and scale up to 3 but the storage path continue empty.

**Comment by cloudnautique** [comment]
@fernandoneto, we only manage the volume when the stack comes up initially. From a user experience perspective, we wanted the stack to come up and immediately be usable. So we create an N node replicated volume, where N is the scale of the stack. After that, when the service is scaled up we will add it to the pool, but not to the volume. So if you do `gluster peer status` or `gluster pool list` you should see your containers getting added. 

We are not managing withdrawing nodes from the cluster or volume repair in the event of node failure.

The stack is really just GlusterFS, and we figured people who deploy it probably want raw Gluster.

**Comment by fernandoneto** [comment]
@cloudnautique thank you for your fast answer.
Don't you think it's better provide some documentation about this limitations to prevent someone else have same doubts ???

**Comment by cloudnautique** [comment]
Yes, we will be supporting README files soon! :) Current API allows for about 1 tweet worth of info.

**Comment by deniseschannon** [comment]
We have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Therefore, I'm going to close this issue.
