### ISSUE TITLE
"Start" stack from catalog; nothing happens

### ISSUE THREAD

**Issue by magsol** [rancher/rancher-catalog#60]
I'm interested in running the Hadoop + YARN template on my Rancher environment. Problem is, when I click to "Launch" the stack, nothing happens. It shows up in my list of stacks as "hadoop" but that's it. How do I start all the services associated with it that I see in the docker-compose yaml file--the namenode, yarn service, hdfs, etc?

This seems like I'm missing something elementary.

**Comment by deniseschannon** [comment]
@magsol If you still have issues launching catalogs in our latest releases, please open an issue in rancher/rancher.
