### ISSUE TITLE
Drone template

### ISSUE THREAD

**Issue by Swatto** [rancher/rancher-catalog#62]
Since you have a meetup recorded on that subject, it could be possible.

**Comment by cloudnautique** [comment]
It is definitely possible :) just haven't had time recently. I want to get a solid Drone 0.4 environment going they did a lot good stuff, which was demoed by Brad at the meetup. The configuration changed a bit, and the adding / removing of nodes go a lot easier. So just need some time to cut over.

**Comment by blackjid** [comment]
hey I would love to have a Drone template... Are you using drone for rancher? or you use some other hosted CI service out there?

**Comment by lkoenigsberger** [comment]
I think this could be closed by commit #98

**Comment by cloudnautique** [comment]
Closing this, as @lkoenigsberger pointed out, #98 provides a drone template.

**Comment by blackjid** [comment]
:+1:
