### ISSUE TITLE
Hadoop as a storage pool 

### ISSUE THREAD

**Issue by lavvy** [rancher/rancher-catalog#65]
Hello any plans to make hadoop as a storage pool ? 
Secondly can hue hadoop manager be added to the hadoop service and even some basic apps like impala etc

**Comment by cloudnautique** [comment]
Do you mean just have HDFS as a standalone catalog entry? Or do you mean deploy something from Convoy to get a local HDFS volume into containers?

**Comment by lavvy** [comment]
Yes.  For us to get local hdfs entry from containers.  That would be very
awesome.
Then hue to view and manage the files in the hdfs

**Comment by lavvy** [comment]
If rancher has a native hdfs entry for the containers @claudnautic ,  that would be super duper duper duper cool. 
 In fact @claudnautic is it something that can be done easily?  or do I open a new issue for it.

**Comment by deniseschannon** [comment]
As hadoop is now a community catalog, please file any issues with hadoop in that repo. 

https://github.com/rancher/community-catalog/tree/master/templates/hadoop
