### ISSUE TITLE
Logstash add grok pattern

### ISSUE THREAD

**Issue by allamand** [rancher/rancher-catalog#66]
Hello,

I'm using logstash from catalog to parse specific application format log.
I Used this site to test my patterns http://grokconstructor.appspot.com/do/match#result

In order to make the parsing work, I had to add some grok patterns, 

==> it would be great if the UI can allow us to add specific pattern.

sébastien

**Comment by cloudnautique** [comment]
Yeah, we can do this. Its supported in the image under the rancher metadata, just forgot to add it to the question list.

**Comment by sebmoule** [comment]
Yes great news Bill ;)

You know when ?

Sébastien

**Comment by sebmoule** [comment]
@cloudnautique, is there a way I can hack this with rancher-agent.yml for now ?

**Comment by cloudnautique** [comment]
In the metadata section the key is patterns. Same level as outputs etc

**Comment by sebmoule** [comment]
something like this ?

logstash-indexer-config:
  scale: 1
  metadata: &id002
    logstash:
      inputs: |+
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }

      patterns:|+
        BRACKET [^\]]*
        GUILLEMET [^\"]*

      filters: |+
        grok {
          patterns_dir => "/etc/logstash/patterns"

seams i'm doing it wrong..

**Comment by cloudnautique** [comment]
The file is placed in /opt/logstash/patterns/extra

Heres the container image repo: https://github.com/rancher/compose-templates/tree/master/logstash/containers/0.2.0/logstash-config

**Comment by sebmoule** [comment]
Thanks i was looking at the image repo but i didn't figure out how to add the extra file or how to add my pattern in it ..

Sébastien

**Comment by cloudnautique** [comment]
Your example above looks correct, I think you were just referencing the wrong location.

**Comment by sebmoule** [comment]
With my example seams to have a yaml parsing error it says missing ":"

I'll try again tomorrow thanks

Sébastien

**Comment by sebmoule** [comment]
@cloudnautique my /opt/logstash/patterns/extra file remains empty..

I added this in my answers.txt file
export patterns='BRACKET [^\]]*
GUILLEMET [^\"]*
'
and patterns section in rancher-compose.yml file 

logstash-indexer:
  metadata:
    logstash:
      inputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
      patterns: |
        ${patterns}
      filters: |
        ${indexer_filters}
      outputs: |
        ${indexer_outputs}

Thanks for your help

**Comment by deniseschannon** [comment]
@allamand I'm not sure the current state of logstash and your current request, but as it's moved to the community catalog. If you have any issues, please open up a new issue there.

https://github.com/rancher/community-catalog/tree/master/templates/logstash
