### ISSUE TITLE
Erreur 422 code=NotUnique when recreating a stack or part of a stack

### ISSUE THREAD

**Issue by allamand** [rancher/rancher-catalog#67]
Hi,

I manage my logstash stack using rancher-client (i've pasted the config from the UI and know manage it directly from the CLI

when I stop/rm the whole stack or just part of it, I can't recreate it i've got this error

ERRO[0000] Failed Creating logstash-collector : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://rancher/v1/services] 

for the whole stack i found a workarround using the UI to delete the empty remaining stack.
But didn't manage to find a workarround it I delete and want to recreate only part of the stack

**Comment by deniseschannon** [comment]
@allamand I'm not sure the current state of logstash and your current issue, but as the template has moved to the community catalog. If you still have any issues, please open up a new issue there.

https://github.com/rancher/community-catalog/tree/master/templates/logstash
