### ISSUE TITLE
[convoy-nfs] Make nfs optional

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher-catalog#74]
Hello,

convoy-nfs uses the vfs backend driver which would also work with local host directories. 
So nfs (server) should be optional to use local host directories for convoy volumes.

**Comment by cusspvz** [comment]
#80 is somehow related with this if there is a chance to choose filesystem and a mount path for the backend.

**Comment by cloudnautique** [comment]
@cjellick, have you seen this one?

**Comment by cjellick** [comment]
I hadn't @cloudnautique. I actually use a local-storage backed convoy-vfs setup for testing. Repo is here:
https://github.com/cjellick/convoy-local and in docker hub under the same name.

But in a real Rancher deployment of convoy-nfs, this would not work well. The convoy-nfs catalog presumes shared storage such that containers running on host A and host B have access to the same volume. So, using host-local storage would result in unexpected behavior for containers consuming the volume.

@pwFoo what's the use case you envision for this? If the idea is that you just want to control where volumes get written to on your host, I could see having a new catalog item like "convoy-local" where we use convoy-vfs + a local dir and create a storage pool per host.

**Comment by pwFoo** [comment]
HI @cjellick, convoy-local would be great. At the moment I have a single host RancherOS / Rancher and nfs isn't necessary.

I builded a similar image used as RancherOS system-docker service. For better usage I added alias to just call it with "convoy".

**Comment by deniseschannon** [comment]
If anyone still has issues with convoy-nfs, please open issues in rancher/rancher as we'll be closing the issues in this repo.
