### ISSUE TITLE
Any example on how to setup convoy with s3 storage?

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher-catalog#80]
Is there any example on how to setup convoy with s3 storage?

**Comment by cusspvz** [comment]
ping @cjellick

**Comment by cjellick** [comment]
@cusspvz we don't support a s3 backend for convoy.
We do support EBS as a backend in [convoy itself](https://github.com/rancher/convoy/blob/master/docs/ebs.md), but we only have catalog items for glusterfs and nfs.

**Comment by cusspvz** [comment]
Ohh, I think I saw somewhere integration with an S3 backend. Sorry, my fault...
