### ISSUE TITLE
convoy-gluster does work with external gluster server

### ISSUE THREAD

**Issue by swaroopkundeti** [rancher/rancher-catalog#84]
Hello There,

I've setup a external service pointing to my gluster server. Then I spinned up convoy-gluster from catalog and attached the external services to it. Looks like convoy-gluster is failing to mount gluster file system.

<b>System configs:</b>
<pre>
Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0
</pre>

<b>Logs:</b>
<pre>
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs]"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.servers:glusterfs glusterfs.defaultvolumepool:synappfiles] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:11 PM{
1/15/2016 3:25:11 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:11 PM}
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:11 PMtime="2016-01-15T09:55:11Z" level=info msg=Exiting.
1/15/2016 3:25:13 PMWaiting for metadatatime="2016-01-15T09:55:13Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/914/ns/mnt -F -- /var/lib/docker/aufs/mnt/2e7f36ac1ee1e5796777316c1449895d910a0c8bf48fc13d87f729055980c767/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 -- /launch volume-agent-glusterfs-internal]"
1/15/2016 3:25:13 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs]"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:synappfiles glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:13 PM{
1/15/2016 3:25:13 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:13 PM}
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:13 PMtime="2016-01-15T09:55:13Z" level=info msg=Exiting.
1/15/2016 3:25:19 PMWaiting for metadata.time="2016-01-15T09:55:19Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/914/ns/mnt -F -- /var/lib/docker/aufs/mnt/2e7f36ac1ee1e5796777316c1449895d910a0c8bf48fc13d87f729055980c767/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 -- /launch volume-agent-glusterfs-internal]"
1/15/2016 3:25:19 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs]"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:synappfiles glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:19 PM{
1/15/2016 3:25:19 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:19 PM}
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:19 PMtime="2016-01-15T09:55:19Z" level=info msg=Exiting.
1/15/2016 3:25:24 PMWaiting for metadata.time="2016-01-15T09:55:24Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/914/ns/mnt -F -- /var/lib/docker/aufs/mnt/2e7f36ac1ee1e5796777316c1449895d910a0c8bf48fc13d87f729055980c767/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 -- /launch volume-agent-glusterfs-internal]"
1/15/2016 3:25:24 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs]"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:synappfiles glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:24 PM{
1/15/2016 3:25:24 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:24 PM}
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:24 PMtime="2016-01-15T09:55:24Z" level=info msg=Exiting.
1/15/2016 3:25:41 PMWaiting for metadata.time="2016-01-15T09:55:41Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/914/ns/mnt -F -- /var/lib/docker/aufs/mnt/2e7f36ac1ee1e5796777316c1449895d910a0c8bf48fc13d87f729055980c767/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 -- /launch volume-agent-glusterfs-internal]"
1/15/2016 3:25:41 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs]"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:synappfiles glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:41 PM{
1/15/2016 3:25:41 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:41 PM}
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:41 PMtime="2016-01-15T09:55:41Z" level=info msg=Exiting.
1/15/2016 3:25:46 PMWaiting for metadata.time="2016-01-15T09:55:46Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/914/ns/mnt -F -- /var/lib/docker/aufs/mnt/2e7f36ac1ee1e5796777316c1449895d910a0c8bf48fc13d87f729055980c767/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 -- /launch volume-agent-glusterfs-internal]"
1/15/2016 3:25:46 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="Got: drivers [glusterfs]"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=synappfiles glusterfs.servers=glusterfs]"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=synappfiles --driver-opts=glusterfs.servers=glusterfs]"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666" pkg=daemon
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:synappfiles glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=debug msg="Volume synappfiles is being mounted it to /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles, with option [-t glusterfs]" pkg=util
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:46 PM{
1/15/2016 3:25:46 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/synappfiles /var/lib/rancher/convoy/convoy-gluster-d9c35987-7d9d-4532-80c1-5a79bb15e666/glusterfs/mounts/synappfiles], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/15/2016 3:25:46 PM}
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg="convoy exited with error: exit status 1"
1/15/2016 3:25:46 PMtime="2016-01-15T09:55:46Z" level=info msg=Exiting.
</pre>

Is there any other workaround, so we could use our glusterfs for storage pools?

**Comment by deniseschannon** [comment]
We have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher.
