### ISSUE TITLE
jenkins-swarm docker error

### ISSUE THREAD

**Issue by sebmoule** [rancher/rancher-catalog#86]
I get in trouble using jenkins-swarm with versions of docker different from my host and inside the debian container see

https://github.com/docker/docker/issues/19230

to fix this i don't mount the docker binary but "manually installed it" with a jenkins job.. maybe we can find a better way..

**Comment by cloudnautique** [comment]
Yeah, I was hoping to avoid packaging Docker. I wonder if the Jenkins docker build plugin uses a client or the binary.

**Comment by cloudnautique** [comment]
@sebmoule, I'll be building a new template based on this rancher/compose-templates#42. Thoughts? The biggest drawback is that its going to require Docker 1.9.1 on the host, and some users might still be on earlier versions.

**Comment by cloudnautique** [comment]
Closing this issue.

**Comment by sebmoule** [comment]
Thanks @cloudnautique i'll test asap ;)
