### ISSUE TITLE
Suggestion: Datadog

### ISSUE THREAD

**Issue by ShakataGaNai** [rancher/rancher-catalog#87]
Adding Datadog (and maybe other similar tools) would be quite useful for the catalog. They already have a Container: https://github.com/DataDog/docker-dd-agent

**Comment by cloudnautique** [comment]
We agree. We have talked with them, and remain hopeful :)

**Comment by janeczku** [comment]
PR just landed: https://github.com/rancher/community-catalog/pull/18

**Comment by deniseschannon** [comment]
As this is in the community catalog, I'll close this issue.
